"""Associate tables with owners

Revision ID: 566e193db997
Revises: b37be0a205d4
Create Date: 2019-11-14 11:33:30.379111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566e193db997'
down_revision = 'b37be0a205d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_table_user_id'), 'table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_user_id'), table_name='table')
    op.drop_column('table', 'user_id')
    # ### end Alembic commands ###
