"""Create dynamic tables

Revision ID: e13b872e5e22
Revises: b25b43456696
Create Date: 2019-10-16 08:43:28.459685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13b872e5e22'
down_revision = 'b25b43456696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('identity', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datatype', sa.String(), nullable=True),
    sa.Column('table', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_column_created_at'), 'column', ['created_at'], unique=False)
    op.create_index(op.f('ix_column_table'), 'column', ['table'], unique=False)
    op.create_table('row',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('table', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_row_created_at'), 'row', ['created_at'], unique=False)
    op.create_index(op.f('ix_row_table'), 'row', ['table'], unique=False)
    op.create_index(op.f('ix_row_uuid'), 'row', ['uuid'], unique=False)
    op.create_table('table',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('identity', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_table_created_at'), 'table', ['created_at'], unique=False)
    op.create_index(op.f('ix_table_identity'), 'table', ['identity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_identity'), table_name='table')
    op.drop_index(op.f('ix_table_created_at'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_row_uuid'), table_name='row')
    op.drop_index(op.f('ix_row_table'), table_name='row')
    op.drop_index(op.f('ix_row_created_at'), table_name='row')
    op.drop_table('row')
    op.drop_index(op.f('ix_column_table'), table_name='column')
    op.drop_index(op.f('ix_column_created_at'), table_name='column')
    op.drop_table('column')
    # ### end Alembic commands ###
