#!/bin/sh -ex

if [ "${CONTINUOUS_INTEGRATION}" = "true" ]; then
    BIN_PATH=""
else
    rm -rf venv
    virtualenv venv --python=python3.7
    BIN_PATH="venv/bin/"
fi

if ! [ -f .env ] ; then
    echo "DEBUG=true" > .env
fi

if [ "$1" = "--update" ]; then
    rm -f requirements.txt
    ${BIN_PATH}pip install -U -r requirements.base
    ${BIN_PATH}pip freeze > requirements.txt
else
    ${BIN_PATH}pip install -U -r requirements.txt
fi
