#!/bin/sh -ex

if [ "${CONTINUOUS_INTEGRATION}" = "true" ]; then
    BIN_PATH=""
else
    rm -rf venv
    virtualenv venv --python=python3.7
    BIN_PATH="venv/bin/"
fi

if [ "$1" = "--update" ]; then
    ${BIN_PATH}pip install -U -r requirements.base
    scripts/freeze
else
    ${BIN_PATH}pip install -U -r requirements.txt
fi
