#!/bin/sh -ex

if [ "${CONTINUOUS_INTEGRATION}" = "true" ]; then
    BIN_PATH=""
else
    BIN_PATH="venv/bin/"
fi

scripts/lint --check
PYTHONPATH=. ${BIN_PATH}pytest tests --cov=source --cov=tests --cov-fail-under=100 --cov-report=term-missing
