#!/bin/sh -ex

if [ "${CONTINUOUS_INTEGRATION}" = "true" ]; then
    BIN_PATH=""
else
    BIN_PATH="venv/bin/"
fi

scripts/lint --check
PYTHONPATH=. ${BIN_PATH}pytest tests -W ignore::DeprecationWarning --cov=source --cov=tests --cov-report=
${BIN_PATH}coverage report --fail-under=100 --show-missing
